#!/usr/bin/env python3
"""MCP server for Swagger Petstore — auto-generated by MCPForge."""

import os
import httpx
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("Swagger Petstore")
BASE_URL = "https://petstore.swagger.io/v2"

# Authentication
PETSTORE_AUTH_TOKEN = os.environ.get("PETSTORE_AUTH_TOKEN", "")  # Bearer token
API_KEY_KEY = os.environ.get("API_KEY_KEY", "")  # API key for api_key header


@mcp.tool()
def uploadfile(petId: int) -> dict:
    """uploads an image"""
    url = f"{BASE_URL}/pet/{petId}/uploadImage"
    headers = {}
    if PETSTORE_AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {PETSTORE_AUTH_TOKEN}"
    resp = httpx.post(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def addpet(body: dict) -> dict:
    """Add a new pet to the store"""
    url = f"{BASE_URL}/pet"
    headers = {}
    if PETSTORE_AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {PETSTORE_AUTH_TOKEN}"
    resp = httpx.post(url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def updatepet(body: dict) -> dict:
    """Update an existing pet"""
    url = f"{BASE_URL}/pet"
    headers = {}
    if PETSTORE_AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {PETSTORE_AUTH_TOKEN}"
    resp = httpx.put(url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def findpetsbystatus(status: list) -> dict:
    """Finds Pets by status"""
    url = f"{BASE_URL}/pet/findByStatus"
    params = {
        "status": status,
    }
    # Remove None values
    params = {k: v for k, v in params.items() if v is not None}
    headers = {}
    if PETSTORE_AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {PETSTORE_AUTH_TOKEN}"
    resp = httpx.get(url, headers=headers, params=params, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def findpetsbytags(tags: list) -> dict:
    """Finds Pets by tags"""
    url = f"{BASE_URL}/pet/findByTags"
    params = {
        "tags": tags,
    }
    # Remove None values
    params = {k: v for k, v in params.items() if v is not None}
    headers = {}
    if PETSTORE_AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {PETSTORE_AUTH_TOKEN}"
    resp = httpx.get(url, headers=headers, params=params, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def getpetbyid(petId: int) -> dict:
    """Find pet by ID"""
    url = f"{BASE_URL}/pet/{petId}"
    headers = {}
    if API_KEY_KEY:
        headers["api_key"] = API_KEY_KEY
    resp = httpx.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def updatepetwithform(petId: int) -> dict:
    """Updates a pet in the store with form data"""
    url = f"{BASE_URL}/pet/{petId}"
    headers = {}
    if PETSTORE_AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {PETSTORE_AUTH_TOKEN}"
    resp = httpx.post(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def deletepet(petId: int, api_key: str = None) -> dict:
    """Deletes a pet"""
    url = f"{BASE_URL}/pet/{petId}"
    headers = {}
    if PETSTORE_AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {PETSTORE_AUTH_TOKEN}"
    if api_key:
        headers["api_key"] = str(api_key)
    resp = httpx.delete(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def getinventory() -> dict:
    """Returns pet inventories by status"""
    url = f"{BASE_URL}/store/inventory"
    headers = {}
    if API_KEY_KEY:
        headers["api_key"] = API_KEY_KEY
    resp = httpx.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def placeorder(body: dict) -> dict:
    """Place an order for a pet"""
    url = f"{BASE_URL}/store/order"
    headers = {}
    resp = httpx.post(url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def getorderbyid(orderId: int) -> dict:
    """Find purchase order by ID"""
    url = f"{BASE_URL}/store/order/{orderId}"
    headers = {}
    resp = httpx.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def deleteorder(orderId: int) -> dict:
    """Delete purchase order by ID"""
    url = f"{BASE_URL}/store/order/{orderId}"
    headers = {}
    resp = httpx.delete(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def createuserswithlistinput(body: dict) -> dict:
    """Creates list of users with given input array"""
    url = f"{BASE_URL}/user/createWithList"
    headers = {}
    resp = httpx.post(url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def getuserbyname(username: str) -> dict:
    """Get user by user name"""
    url = f"{BASE_URL}/user/{username}"
    headers = {}
    resp = httpx.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def updateuser(username: str, body: dict) -> dict:
    """Updated user"""
    url = f"{BASE_URL}/user/{username}"
    headers = {}
    resp = httpx.put(url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def deleteuser(username: str) -> dict:
    """Delete user"""
    url = f"{BASE_URL}/user/{username}"
    headers = {}
    resp = httpx.delete(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def loginuser(username: str, password: str) -> dict:
    """Logs user into the system"""
    url = f"{BASE_URL}/user/login"
    params = {
        "username": username,
        "password": password,
    }
    # Remove None values
    params = {k: v for k, v in params.items() if v is not None}
    headers = {}
    resp = httpx.get(url, headers=headers, params=params, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def logoutuser() -> dict:
    """Logs out current logged in user session"""
    url = f"{BASE_URL}/user/logout"
    headers = {}
    resp = httpx.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def createuserswitharrayinput(body: dict) -> dict:
    """Creates list of users with given input array"""
    url = f"{BASE_URL}/user/createWithArray"
    headers = {}
    resp = httpx.post(url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}


@mcp.tool()
def createuser(body: dict) -> dict:
    """Create user"""
    url = f"{BASE_URL}/user"
    headers = {}
    resp = httpx.post(url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status_code": resp.status_code, "text": resp.text}

if __name__ == "__main__":
    mcp.run()
